"""One visual language for every figure in the paper.

Figures that are generated by different scripts still have to read as one set:
the same typeface, the same weights, and — most importantly — the same colour
meaning the same thing everywhere. A reviewer who learns that teal is "our
system" on Figure 1 should not have to relearn it on Figure 4.

Import ``apply()`` at the top of a chart script, and take colours from
``SYSTEM``/``STATUS`` rather than writing hex literals inline.
"""

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

# Systems under comparison. Teal is always "the pipeline in this release";
# grey is always an unaugmented baseline.
SYSTEM = {
    "ours": "#00897b",       # this release (v3.2.0 pipeline)
    "previous": "#5c6bc0",   # an earlier version of our own pipeline
    "baseline": "#9e9e9e",   # raw model, no pipeline
    "external": "#e65100",   # a third-party system
}

# Outcome of a graded problem. Consistent across every results figure.
STATUS = {
    "correct": "#2e7d32",
    "wrong": "#c62828",
    "timeout": "#f9a825",
    "error": "#8d6e63",
}

TEXT = "#212121"
MUTED = "#616161"
GRID = "#cfd8dc"


def apply() -> None:
    """Install the shared rcParams. Call once, before creating any figure."""
    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 11,
        "text.color": TEXT,
        "axes.labelcolor": TEXT,
        "axes.edgecolor": MUTED,
        "axes.labelsize": 11,
        "axes.titlesize": 12,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "legend.frameon": False,
        "legend.fontsize": 10,
        "grid.color": GRID,
        "figure.dpi": 150,
        "savefig.dpi": 150,
        "savefig.bbox": "tight",
    })


def headroom(ax, top: float, factor: float = 1.28) -> None:
    """Reserve vertical space above ``top`` for value labels.

    ``ax.margins(y=...)`` is silently a no-op on a stacked bar chart: every
    ``bar()`` call registers a sticky edge at y=0, and matplotlib then declines
    to add any margin on that axis at all. Annotations drawn at the top of the
    bars end up outside the axes, overprinting the title. Setting the limit
    explicitly is the only reliable fix.
    """
    ax.set_ylim(0, top * factor if top > 0 else 1)


def footnote(fig, text: str) -> None:
    """Add a small caption strip under the figure for methodology notes."""
    fig.text(0.5, -0.02, text, ha="center", va="top", fontsize=8.5, color=MUTED)
